config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  namespace :doctors do
    resources :sessions, only: [:new, :create, :destroy] # for doctors login/logout
    resources :registrations, only: [:new, :create] # for doctors signup
    delete 'logout', to: 'sessions#destroy', as: 'logout' 
  end
  
  namespace :patients do
    resources :sessions, only: [:new, :create, :destroy] # for patients login/logout
    resources :registrations, only: [:new, :create] # for patients signup
    delete 'logout', to: 'sessions#destroy', as: 'logout' 
  end

  resources :patients do
    resources :appointments, only: [:new, :create, :show, :destroy] do
      resources :patient_diagnoses, only: [:new, :create]  
      collection do
        get :choose_time
        post :finalize
      end
    end
    resources :medications, only: [:index, :create]
    resources :diagnoses, only: [:index, :create]
  end
  

  resources :doctors, except: [:show] do
    resources :patients, only: [:new, :create, :show]
    resources :appointments, only: [:index, :create]
  end
  
  get 'dashboard', to: 'patients#dashboard', as: 'dashboard'
  get 'doctors/:id/daily_patients', to: 'doctors#daily_patients', as: 'daily_patients_doctor'
  post '/diagnosticForm/:patient_id', to: 'patient_diagnoses#create', as: 'diagnostic_form'
  get '/diagnosticForm/:patient_id/new', to: 'patient_diagnoses#new', as: 'new_patient_diagnosis'
  get '/diagnosis/:id/scheduler', to: 'patient_diagnoses#scheduler', as: 'scheduler_patient_diagnosis'
  post '/diagnosis/:id/confirm_schedule', to: 'patient_diagnoses#confirm_schedule', as: 'confirm_schedule_patient_diagnosis'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validates :appointment_time, uniqueness: { scope: [:doctor_id, :appointment_date] }

  scope :today, -> { where(appointment_date: Date.current.beginning_of_day..Date.current.end_of_day) }
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
   # Ensure the patient is logged in for all actions in this controller
  before_action :logged_in_patient

  # Prepare for creating a new appointment
  def new
    @patient = current_patient
    # Build a new blank appointment for the form
    @appointment = Appointment.new
    @doctors = Doctor.all
    # Retrieve the latest suggested appointment from the aischeduler table where "has_taken_appointment" is false
    @suggested_appointment = @patient.ai_schedulers.where(has_taken_appointment: false).order(created_at: :desc).first
    if @suggested_appointment
      @suggested_date = @suggested_appointment.date
      @doctor = @suggested_appointment.doctor
      # Define the range of possible appointment times, from 9 to 20, excluding 13
      @all_times = (9..12).to_a + (14..20).to_a
      # Find when the doctor already has appointments on the suggested date
      existing_appointment_times = @doctor.appointments.where(appointment_date: @suggested_date).pluck(:appointment_time).map { |time| time.hour }
      # Determine the times when the doctor is available
      @available_times = @all_times - existing_appointment_times
    end
  end
  
  
  
   # Process the form submission for creating a new appointment
   def create
    @patient = current_patient
    @doctor = Doctor.find(params[:appointment][:doctor_id])
    @suggested_appointment = @patient.ai_schedulers.order(created_at: :desc).first
    # Check if a date was chosen for the appointment
    if params[:appointment][:appointment_date].present?
      # If a date was chosen, store it in the session
      session[:appointment_date] = params[:appointment][:appointment_date]
      # Redirect to the time selection page
      redirect_to choose_time_patient_appointments_path(patient_id: @patient.id, doctor_id: @doctor.id)
    else
      # If no date was chosen, display an error
      @doctors = Doctor.all
      flash.now[:error] = "Please choose a date for your appointment."
      render :new
    end
  end

   # Prepare to select a time for the appointment
  def choose_time
      # Calls the prepare_appointment method to set up necessary variables for appointment creation
    prepare_appointment
  end
  
   # Process the form submission for finalizing an appointment
   def finalize
    # Fetch the current logged-in patient
    @patient = current_patient
    # Build a new appointment instance using parameters from the form
    @appointment = @patient.appointments.new(appointment_params)
    @appointment.patient_id = @patient.id
    # Fetch the latest AiScheduler instance for the patient
    suggested_appointment = @patient.ai_schedulers.order(created_at: :desc).first
    # Attempt to save the appointment
    if @appointment.save!
      # If successful, remove the appointment date from the session and display a success message
      session.delete(:appointment_date)
      flash[:success] = "Appointment was successfully created."
      # Update the AiScheduler instance if this appointment matches the suggested one
      if suggested_appointment.present? && 
         suggested_appointment.doctor_id == @appointment.doctor_id && 
         suggested_appointment.date == @appointment.appointment_date
        suggested_appointment.update(has_taken_appointment: true)
      end
      redirect_to dashboard_path
    else
      # If unsuccessful, display an error message and render the choose_time view again
      flash.now[:error] = "An error occurred while creating the appointment."
      prepare_appointment
      render :choose_time
    end
  end
  
  
  private

   # Set up necessary variables for appointment creation and time selection
   def prepare_appointment
    # Fetch the chosen doctor and current patient
    @doctor = Doctor.find(params[:doctor_id])
    @patient = current_patient
    # Build a new appointment for the current patient and chosen doctor
    @appointment = @patient.appointments.build(doctor: @doctor)
    # Parse the chosen date from the session
    @appointment_date = Date.parse(session[:appointment_date])
    # Define the range of possible appointment times
    @all_times = (9..12).to_a + (14..20).to_a
    # Find when the doctor already has appointments on the chosen date
    existing_appointment_times = @doctor.appointments.where(appointment_date: @appointment_date).pluck(:appointment_time).map { |time| time.hour }
    # Determine the times when the doctor is available
    @available_times = @all_times - existing_appointment_times
  end

  # Ensure the patient is logged in
  def logged_in_patient
    # If the patient is not logged in, display an error and redirect to the login page
    unless current_patient.present?
      flash[:danger] = "You need to log in to view appointments"
      redirect_to patients_sessions_path
    end
  end

  # Define the parameters allowed for creating an appointment
  def appointment_params  
    params.require(:appointment).permit(:appointment_date, :appointment_time, :doctor_id, :patient_id)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_followup.html.erb
<h2>Follow-Up Appointment</h2>
<%= form_for([@patient, @appointment], url: finalize_patient_appointments_path(@patient)) do |f| %>
  <table class="dashboard-table">
    <thead>
      <tr>
        <th>Recommended Doctor</th>
        <th>Diagnosis</th>
        <th>Recommended appointment date</th>
        <th>Choose a time for your appointment:</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @suggested_appointment.doctor.full_name %></td>
        <%= f.hidden_field :doctor_id, value: @suggested_appointment.doctor.id %>

        <td><%= @suggested_appointment.patient_diagnosis.diagnosis.name %></td>
        
        <td><%= @suggested_appointment.date.strftime("%m-%d-%Y") %></td>
        <%= f.hidden_field :appointment_date, value: @suggested_appointment.date %>
        
        <td><%= f.select :appointment_time, options_for_select(@available_times.map { |t| [t.to_s + ":00", t] }), {}, prompt: "Select a time" %></td>
        <td><%= f.submit "Confirm Appointment", class: "button-17" %></td>
      </tr>
    </tbody>
  </table>
 
<% end %>

app/views/appointments/choose_time.html.erb
<%= form_for @appointment, url: finalize_patient_appointments_path(@patient) do |f| %>
  <%= f.hidden_field :doctor_id, value: @doctor.id %>
  <%= f.hidden_field :appointment_date, value: @appointment_date %>
  <%= f.label :appointment_time, "Choose a time for your appointment:" %>
  <%= f.select :appointment_time, options_for_select(@available_times.map { |t| [t.to_s + ":00", t] }), {}, prompt: "Select a time" %>
  
  <%= f.submit "Create Appointment", class: "button-17" %>
<% end %>

<% if @appointment %>
<% @appointment.errors.full_messages.each do |msg| %>
  <p>
  <%= msg %>
  </p>
  <% end %>
<% end %>

app/views/appointments/new.html.erb
<% if @suggested_appointment.present? %>
  <%= render 'followup', suggested_appointment: @suggested_appointment, available_times: @available_times %>
<% end %>

<h2>Book New Appointment Date</h2>

<%= form_for([@patient, @appointment]) do |f| %>
  <%= f.label :doctor_id, "Choose a doctor:" %>
  <%= f.collection_select(:doctor_id, @doctors, :id, :full_name, prompt: "Select a doctor") %>

  <%= f.label :appointment_date, "Choose a date for your appointment:" %>
  <%= f.date_field :appointment_date, id: "appointment-date", :readonly => true%>
  <div  id="my-calendar" ></div>
  
  <%= f.submit "Proceed to select appointment time",class: "button-17" %>
<% end %>