config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  namespace :doctors do
    resources :sessions, only: [:new, :create, :destroy] # for doctors login/logout
    resources :registrations, only: [:new, :create] # for doctors signup
    delete 'logout', to: 'sessions#destroy', as: 'logout' 
  end
  
  namespace :patients do
    resources :sessions, only: [:new, :create, :destroy] # for patients login/logout
    resources :registrations, only: [:new, :create] # for patients signup
    delete 'logout', to: 'sessions#destroy', as: 'logout' 
  end

  resources :patients do
    resources :appointments, only: [:new, :create, :show, :destroy] do
      resources :patient_diagnoses, only: [:new, :create]  
      collection do
        get :choose_time
        post :finalize
      end
    end
    resources :medications, only: [:index, :create]
    resources :diagnoses, only: [:index, :create]
  end
  

  resources :doctors, except: [:show] do
    resources :patients, only: [:new, :create, :show]
    resources :appointments, only: [:index, :create]
  end
  
  get 'dashboard', to: 'patients#dashboard', as: 'dashboard'
  get 'doctors/:id/daily_patients', to: 'doctors#daily_patients', as: 'daily_patients_doctor'
  post '/diagnosticForm/:patient_id', to: 'patient_diagnoses#create', as: 'diagnostic_form'
  get '/diagnosticForm/:patient_id/new', to: 'patient_diagnoses#new', as: 'new_patient_diagnosis'
  get '/diagnosis/:id/scheduler', to: 'patient_diagnoses#scheduler', as: 'scheduler_patient_diagnosis'
  post '/diagnosis/:id/confirm_schedule', to: 'patient_diagnoses#confirm_schedule', as: 'confirm_schedule_patient_diagnosis'
end

app/models/ai_scheduler.rb
class AiScheduler < ApplicationRecord
  belongs_to :patient
  belongs_to :patient_diagnosis
  belongs_to :doctor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validates :appointment_time, uniqueness: { scope: [:doctor_id, :appointment_date] }

  scope :today, -> { where(appointment_date: Date.current.beginning_of_day..Date.current.end_of_day) }
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  has_many :patient_diagnoses
  has_many :patients, through: :patient_diagnoses
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_secure_password
  belongs_to :hospital
  has_many :appointments
  has_many :patients, through: :appointments
  has_many :ai_schedulers

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors
end

app/models/medication.rb
class Medication < ApplicationRecord
  has_many :patient_medications
  has_many :patients, through: :patient_medications
  has_many :patient_diagnoses, through: :patient_medications
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_secure_password
  has_many :patient_diagnoses
  has_many :diagnoses, through: :patient_diagnoses
  has_many :appointments
  has_many :patient_medications
  has_many :medications, through: :patient_medications
  has_many :ai_schedulers
end

app/models/patient_diagnosis.rb
class PatientDiagnosis < ApplicationRecord
  belongs_to :patient
  belongs_to :diagnosis
  has_one :ai_scheduler
  has_many :patient_medications
  has_many :medications, through: :patient_medications
end

app/models/patient_medication.rb
class PatientMedication < ApplicationRecord
  belongs_to :patient
  belongs_to :medication
  belongs_to :patient_diagnosis, optional: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def new
    @doctor = Doctor.new
  end

  def daily_patients
    @doctor = Doctor.includes(appointments: :patient).find(params[:id])
    @appointments = @doctor.appointments.where(appointment_date: Date.today).order(:appointment_time)
  end

  private
  def doctor_params
    params.require(:doctor).permit(:name, :specialization, :email, :address)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_patient!
  before_action :restrict_patient!, only: [:edit, :update, :destroy]

  def dashboard
    @patient = current_patient
    @appointments = current_patient.appointments.order(appointment_date: :desc, appointment_time: :desc).limit(5)
    @patient_medications = current_patient.patient_medications.joins(:medication).order('expiration_date DESC, medications.brand_name ASC').limit(5)
    @diagnoses = @patient.patient_diagnoses.joins(:diagnosis)
      .select('DISTINCT ON(patient_diagnoses.diagnosis_id) patient_diagnoses.*, diagnoses.name, diagnoses.is_chronic AS is_chronic')
      .order('patient_diagnoses.diagnosis_id, is_chronic DESC, patient_diagnoses.created_at DESC')
      .limit(5)
  end         

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :email, :date_of_birth, :address, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/_nav_doctor.erb
<!-- Doctor is logged in, show appointment and medication options -->
<ul class="nav-item dropdown">
  <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
    User
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Logout', doctors_logout_path, method: :delete, class: "dropdown-item" %></li>
  </ul>
</ul>

app/views/layouts/_nav_patient.erb
<!-- Patient is logged in, show appointment and medication options -->
<!-- Wrap appointments and medication options in a div for styling and centering -->
<div class="patient-links">
  <ul class="nav-item">
    <a class="nav-link patient-link" href="<%= new_patient_appointment_path(current_patient) %>">New Appointment</a>
  </ul>
  <ul class="nav-item">
    <a class="nav-link patient-link" href="<%= patient_medications_path(current_patient) %>">Medication</a>
  </ul>
</div>
<ul class="nav-item dropdown">
  <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
    User
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Logout', patients_logout_path, method: :delete, class: "dropdown-item" %></li>
  </ul>
</ul>

app/views/layouts/_top_nav.erb
<nav class="navbar">
  <a class="navbar-brand" href="<%= session[:patient_id] ? dashboard_path : (session[:doctor_id] ? daily_patients_doctor_path(session[:doctor_id]) : root_path) %>">CanPulse</a>
  <div class="navbar-nav">
    <% if session[:patient_id] %>
      <%= render partial: 'layouts/nav_patient' %>
    <% elsif session[:doctor_id] %>
      <%= render partial: 'layouts/nav_doctor' %>
    <% else %>
      <ul class="nav-item dropdown">
        <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
          Patients
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Login', new_patients_session_path %></li>
          <li><%= link_to 'Sign Up', new_patients_registration_path %></li>
        </ul>
      </ul>
      <ul class="nav-item dropdown">
        <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
          Doctors
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Login', new_doctors_session_path %></li>
          <li><%= link_to 'Sign Up', new_doctors_registration_path %></li>
        </ul>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CanPulse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,600;0,700;0,800;0,900;1,600;1,700;1,800;1,900&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload', defer: true %>
  <%= render 'application/favicon' %>
  
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kanit&family=Russo+One&display=swap" rel="stylesheet">
  </head>

  <body>
  <%= render 'layouts/top_nav' %>
  <main class="main-content">  
    <%= yield %>
  </main>
</body>
</html>

  